version: '3.1'

services:

  frontend:
    build: ./src/frontend
    ports:
      - 80:8501
      - 5678:5678 # Debug port
    container_name: Frotend-IceCreamEmpire
    networks:
      - postgres-network
    volumes:
      - ./src/frontend/:/frontend/

  database:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    container_name: postgres-IceCreamEmpire
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: IceCreamEmpire
    networks:
      - postgres-network
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./pgdata:/var/lib/postgresql/data

  adminer:
      image: adminer
      restart: always
      ports:
          - 1234:8080
      container_name: Adminer-IceCreamEmpire
      networks:
        - postgres-network
      depends_on:
          - "database"
      
networks: 
  postgres-network:
    driver: bridge