version: '3.1'

services:

  frotend:
    build: ./src/frontend
    ports:
      - 80:8501
    container_name: Frotend-IceCreamEmpire
    networks:
      - postgres-network

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    container_name: postgres-IceCreamEmpire
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: IceCreamEmpire
    networks:
      - postgres-network
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./db-data/:/var/lib/postgresql/2-data

  adminer:
      image: adminer
      restart: always
      ports:
          - 1234:8080
      container_name: Adminer-IceCreamEmpire
      networks:
        - postgres-network
      depends_on:
          - "database"
      
networks: 
  postgres-network:
    driver: bridge